### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by fisforfaheem** [arnold-parge/hawk_fab_menu#11]
![image](https://user-images.githubusercontent.com/35878088/122672150-7b384a00-d1e3-11eb-9edb-abb07be6e6fb.png)

**Comment by arnold-parge** [comment]
Could you please send the code snippet of how you have used the `HawkFabMenu`?

**Comment by arnold-parge** [comment]
Since there is no reply, I am closing this issue. If the issue persists, please reopen this issue.

**Comment by fisforfaheem** [comment]
Sorry by the time u replied I stopped using in my code.. and did something else... Please see my code in my repo its open. FLUTTER SCOIAL APP
