### ISSUE TITLE
Expose heroTag of the FloatingActionButton inner widget. 

### ISSUE THREAD

**Issue by mdryankov** [arnold-parge/hawk_fab_menu#12]
The reason is that it will produce exception  in case this widget (or FloatingActionButton) is reused within the navigation stack with a default heroTag value

**Comment by arnold-parge** [comment]
Thanks for pointing it out. Will look into it. 👍🏼

**Comment by mdryankov** [comment]
Thanks @arnold-parge! I appreciate
