### ISSUE TITLE
Close fab programmatically 

### ISSUE THREAD

**Issue by mrSingh007** [arnold-parge/hawk_fab_menu#16]
Currently its not possible to close the Menu if user click on side-bar (Burger Menu).  So as soon as user open drawer (side bar)  I want to close the Fab Menu.   Even AppBar could have filters where click should close the FabMenu. So how can we close the opened FabMenu ? 

```
Scaffold(
      appBar: AppBar(...),
      drawer: Drawer(
        child: burgerMenuItems()
      ),
      body: HawkFabMenu( .... ),
    );
```

**Comment by arnold-parge** [comment]
Added the feature in [v1.2.0](https://github.com/arnold-parge/hawk_fab_menu/releases/tag/v1.2.0).
