### ISSUE TITLE
the shadow of the buttons, customizable

### ISSUE THREAD

**Issue by roberto-ingenito** [arnold-parge/hawk_fab_menu#2]

**Comment by arnold-parge** [comment]
@robi2908 Please provide more information as to which button's shadow exactly.
Or if you can do it, please fork and create PR.

**Comment by xnio94** [comment]
i think his talking about the shadow that applies to the body when the user clicks the button
for some use cases  its better to not have it 
https://photos.app.goo.gl/rzwVUMGiQSDagtDA9

**Comment by arnold-parge** [comment]
Thanks, added in `v1.1.0` 🎉 

You set the properties as below if you wish to not have a background

        blur: 0,
        backgroundColor: Colors.transparent,
