### ISSUE TITLE
Ability to change icon after the FabMenu is opened,

### ISSUE THREAD

**Issue by UmairJibran** [arnold-parge/hawk_fab_menu#4]
I'm sorry if it exists already but I couldn't find it, can you please add the ability to change Icon from that calendar thingy to user-defined icon?

btw thanks for this awesome package!

**Comment by arnold-parge** [comment]
Thanks for the appreciation. Keep suggesting awesome features to add 🚀 .

**This is fixed** in https://github.com/arnold-parge/hawk_fab_menu/issues/3.
Hence closing.
